addons:
  apt:
    packages:
    - clang-3.8
    - lib32stdc++6
    - lib32z1-dev
    - libc6-dev-i386
    - linux-libc-dev
    - gcc-multilib
    - g++-multilib
    sources:
    - llvm-toolchain-precise-3.8
    - ubuntu-toolchain-r-test
language: cpp
branches:
  only:
    - master
compiler:
  - clang
before_script:
  - sudo wget $OSX_CROSS_TOOL -O /tmp/osxcross.tgz && mkdir -p /tmp/osxcross/target && tar xzf /tmp/osxcross.tgz -C /tmp/osxcross/target/
  - export PATH=$PATH:/tmp/osxcross/target/bin
  - wget https://yapb.jeefo.net/ci/scripts/gitrev.sh && chmod a+x ./gitrev.sh && ./gitrev.sh
script:
  - cd project && CC=clang-3.8 make all
after_success:
  - curl --ftp-create-dirs -T ./release/yapb.so -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/release/yapb.so
  - curl --ftp-create-dirs -T ./debug/yapb.so -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/debug/yapb.so
  - curl --ftp-create-dirs -T ./release/yapb.dylib -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/release/yapb.dylib
  - curl --ftp-create-dirs -T ./debug/yapb.dylib -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/debug/yapb.dylib
  - curl -X GET "https://yapb.ru/agent/packager.php?key=$PACKAGER_KEY&os=posix"
  
